/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package checker;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JLabel;
/**
 *
 * @author Rey
 */
public class password extends javax.swing.JFrame {
private JTextField textFieldNombre;
	private JTextField textFieldPassword;
	private JTextField textFieldHoraIni;
	private JTextField textFieldHoraFin;
		
    /**
     * Creates new form password
     */
    public password() {
        getContentPane().setLayout(null);
        
		setVisible(true);
		textFieldNombre = new JTextField();
		textFieldNombre.setBounds(133, 27, 86, 30);
		getContentPane().add(textFieldNombre);
		textFieldNombre.setColumns(10);
		
		textFieldPassword = new JTextField();
		textFieldPassword.setBounds(133, 75, 86, 30);
		getContentPane().add(textFieldPassword);
		textFieldPassword.setColumns(10);
		
		textFieldHoraIni = new JTextField();
		textFieldHoraIni.setBounds(133, 130, 86, 30);
		getContentPane().add(textFieldHoraIni);
		textFieldHoraIni.setColumns(10);
		
		textFieldHoraFin = new JTextField();
		textFieldHoraFin.setBounds(133, 177, 86, 30);
		getContentPane().add(textFieldHoraFin);
		textFieldHoraFin.setColumns(10);
                JButton btnNewButton = new JButton("Check");
		btnNewButton.setBounds(130, 251, 89, 23);
		getContentPane().add(btnNewButton);
		
		final JTextArea textArea = new JTextArea();
		textArea.setEditable(false);
		textArea.setBounds(105, 306, 168, 81);
		getContentPane().add(textArea);
		
		JLabel lblNombre = new JLabel("Nombre");
		lblNombre.setBounds(38, 30, 46, 14);
		getContentPane().add(lblNombre);
		
		JLabel lblPassword = new JLabel("Password");
		lblPassword.setBounds(38, 78, 86, 14);
		getContentPane().add(lblPassword);
		
		JLabel lblHoraEntrada = new JLabel("Hora de entrada");
		lblHoraEntrada.setBounds(38, 133, 96, 14);
		getContentPane().add(lblHoraEntrada);
		
		JLabel lblHoraFinal = new JLabel("Hora de salida");
		lblHoraFinal.setBounds(38, 180, 96, 14);
		getContentPane().add(lblHoraFinal);
		
		btnNewButton.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            {
                //Execute when button is pressed
            	
            	if("".equals(textFieldNombre.getText() )){
            		JOptionPane.showMessageDialog(null, "El nombre no puede estar vacio");
            		return;
            	}
            	else{
            	textArea.setText(textFieldNombre.getText() +"\n" +
            			textFieldPassword.getText() + "\n" +
            			textFieldHoraFin.getText()+"\n" +
            			textFieldHoraIni.getText()+ "\n");
            	}
            }
        });      
 
		
	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
